services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    restart: always
    command: /etc/rabbitmq/bootstrap.sh
    environment:
      - RABBITMQ_DEFAULT_USER=dtunnel
      - RABBITMQ_DEFAULT_PASS=DTunnel01
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
      - ./bootstrap.sh:/etc/rabbitmq/bootstrap.sh:ro
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - network
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: 512M

networks:
  network:
    name: 'rabbitmq_net'
    driver: 'bridge'

volumes:
  rabbitmq_data:
    name: 'rabbitmq_data'
  rabbitmq_log:
    name: 'rabbitmq_log'
