version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=DuTra01?
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - rabbitmq_net
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: 512M

networks:
  rabbitmq_net:
    external: true

volumes:
  rabbitmq_data:
  rabbitmq_log:
